# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import helloworld_pb2 as helloworld__pb2


class GetterStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetIMDBData = channel.unary_unary(
                '/helloworld.Getter/GetIMDBData',
                request_serializer=helloworld__pb2.Request.SerializeToString,
                response_deserializer=helloworld__pb2.Result.FromString,
                )


class GetterServicer(object):
    """The greeting service definition.
    """

    def GetIMDBData(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GetterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetIMDBData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIMDBData,
                    request_deserializer=helloworld__pb2.Request.FromString,
                    response_serializer=helloworld__pb2.Result.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'helloworld.Getter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Getter(object):
    """The greeting service definition.
    """

    @staticmethod
    def GetIMDBData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/helloworld.Getter/GetIMDBData',
            helloworld__pb2.Request.SerializeToString,
            helloworld__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
