# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: helloworld.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10helloworld.proto\x12\nhelloworld\"\x1c\n\x07Request\x12\x11\n\trowOffset\x18\x01 \x01(\x05\"\xb2\x01\n\x03Row\x12\x0e\n\x06tconst\x18\x01 \x01(\t\x12\x11\n\ttitleType\x18\x02 \x01(\t\x12\x14\n\x0cprimaryTitle\x18\x03 \x01(\t\x12\x15\n\roriginalTitle\x18\x04 \x01(\t\x12\x0f\n\x07isAdult\x18\x05 \x01(\x08\x12\x11\n\tstartYear\x18\x06 \x01(\t\x12\x0f\n\x07\x65ndYear\x18\x07 \x01(\t\x12\x16\n\x0eruntimeMinutes\x18\x08 \x01(\t\x12\x0e\n\x06genres\x18\t \x01(\t\"*\n\x06Result\x12 \n\x07results\x18\x01 \x03(\x0b\x32\x0f.helloworld.Row2B\n\x06Getter\x12\x38\n\x0bGetIMDBData\x12\x13.helloworld.Request\x1a\x12.helloworld.Result\"\x00\x42\x36\n\x1bio.grpc.examples.helloworldB\x0fHelloWorldProtoP\x01\xa2\x02\x03HLWb\x06proto3')



_REQUEST = DESCRIPTOR.message_types_by_name['Request']
_ROW = DESCRIPTOR.message_types_by_name['Row']
_RESULT = DESCRIPTOR.message_types_by_name['Result']
Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'helloworld_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.Request)
  })
_sym_db.RegisterMessage(Request)

Row = _reflection.GeneratedProtocolMessageType('Row', (_message.Message,), {
  'DESCRIPTOR' : _ROW,
  '__module__' : 'helloworld_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.Row)
  })
_sym_db.RegisterMessage(Row)

Result = _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), {
  'DESCRIPTOR' : _RESULT,
  '__module__' : 'helloworld_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.Result)
  })
_sym_db.RegisterMessage(Result)

_GETTER = DESCRIPTOR.services_by_name['Getter']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\033io.grpc.examples.helloworldB\017HelloWorldProtoP\001\242\002\003HLW'
  _REQUEST._serialized_start=32
  _REQUEST._serialized_end=60
  _ROW._serialized_start=63
  _ROW._serialized_end=241
  _RESULT._serialized_start=243
  _RESULT._serialized_end=285
  _GETTER._serialized_start=287
  _GETTER._serialized_end=353
# @@protoc_insertion_point(module_scope)
